# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmi.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 776)
        MainWindow.setStyleSheet("background-color: #66ffff")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calc_btn.setGeometry(QtCore.QRect(490, 489, 151, 41))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(16)
        self.calc_btn.setFont(font)
        self.calc_btn.setStyleSheet("background-color: #e6ffff")
        self.calc_btn.setShortcut("")
        self.calc_btn.setObjectName("calc_btn")
        self.height = QtWidgets.QLineEdit(self.centralwidget)
        self.height.setGeometry(QtCore.QRect(150, 220, 251, 71))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(20)
        self.height.setFont(font)
        self.height.setStyleSheet("background-color: white;\n"
"border: 1px solid black")
        self.height.setAlignment(QtCore.Qt.AlignCenter)
        self.height.setObjectName("height")
        self.weight = QtWidgets.QLineEdit(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(720, 220, 251, 71))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(20)
        self.weight.setFont(font)
        self.weight.setStyleSheet("background-color: white;\n"
"border: 1px solid black")
        self.weight.setText("")
        self.weight.setAlignment(QtCore.Qt.AlignCenter)
        self.weight.setObjectName("weight")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(190, 300, 211, 171))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName("groupBox")
        self.meterUnit = QtWidgets.QRadioButton(self.groupBox)
        self.meterUnit.setGeometry(QtCore.QRect(100, 50, 95, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.meterUnit.setFont(font)
        self.meterUnit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.meterUnit.setObjectName("meterUnit")
        self.centimeterUnit = QtWidgets.QRadioButton(self.groupBox)
        self.centimeterUnit.setGeometry(QtCore.QRect(100, 90, 95, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.centimeterUnit.setFont(font)
        self.centimeterUnit.setObjectName("centimeterUnit")
        self.inchUnit = QtWidgets.QRadioButton(self.groupBox)
        self.inchUnit.setGeometry(QtCore.QRect(100, 130, 95, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.inchUnit.setFont(font)
        self.inchUnit.setObjectName("inchUnit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(760, 300, 211, 171))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.kgUnit = QtWidgets.QRadioButton(self.groupBox_2)
        self.kgUnit.setGeometry(QtCore.QRect(100, 50, 95, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.kgUnit.setFont(font)
        self.kgUnit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.kgUnit.setObjectName("kgUnit")
        self.gramUnit = QtWidgets.QRadioButton(self.groupBox_2)
        self.gramUnit.setGeometry(QtCore.QRect(100, 90, 95, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.gramUnit.setFont(font)
        self.gramUnit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gramUnit.setObjectName("gramUnit")
        self.poundUnit = QtWidgets.QRadioButton(self.groupBox_2)
        self.poundUnit.setGeometry(QtCore.QRect(100, 130, 95, 20))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        self.poundUnit.setFont(font)
        self.poundUnit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.poundUnit.setObjectName("poundUnit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 10, 271, 121))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 100, 271, 81))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.outTxt = QtWidgets.QLabel(self.centralwidget)
        self.outTxt.setGeometry(QtCore.QRect(50, 545, 1021, 171))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(36)
        self.outTxt.setFont(font)
        self.outTxt.setText("")
        self.outTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.outTxt.setObjectName("outTxt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1125, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.calc_btn.clicked.connect(self.calcClick)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calc_btn.setText(_translate("MainWindow", "محاسبه"))
        self.height.setPlaceholderText(_translate("MainWindow", "قد خود را وارد کنید"))
        self.weight.setPlaceholderText(_translate("MainWindow", "وزن خود را وارد کنید"))
        self.groupBox.setTitle(_translate("MainWindow", " :واحد طول مورد نظر "))
        self.meterUnit.setText(_translate("MainWindow", "متر"))
        self.centimeterUnit.setText(_translate("MainWindow", "سانتی متر"))
        self.inchUnit.setText(_translate("MainWindow", "اینچ"))
        self.groupBox_2.setTitle(_translate("MainWindow", "  :واحد وزن مورد نظر "))
        self.kgUnit.setText(_translate("MainWindow", "کیلوگرم"))
        self.gramUnit.setText(_translate("MainWindow", "گرم"))
        self.poundUnit.setText(_translate("MainWindow", "پوند"))
        self.label.setText(_translate("MainWindow", " محاسبۀ BMI"))
        self.label_2.setText(_translate("MainWindow", " (شاخص تودۀ بدنی)"))


    def calcClick(self):
        errors = []
        try:
            weight = float(self.weight.text())
            height = float(self.height.text())
        except:
            errors.append("مقادیر ورودی مجاز، مقادیر عددی هستند!")
        meter = self.meterUnit.isChecked()
        centimeter = self.centimeterUnit.isChecked()
        inch = self.inchUnit.isChecked()
        kgram = self.kgUnit.isChecked()
        gram = self.gramUnit.isChecked()
        pound = self.poundUnit.isChecked()
        

        if centimeter:
            height /= 100
        elif inch:
            height *= 0.0254
        elif meter != True:
            errors.append("واحدی برای قد انتخاب کنید!")

        if gram:
            weight /= 1000
        elif pound:
            weight *= 0.4535
        elif kgram != True:
            errors.append("واحدی برای وزن انتخاب کنید!")
        
        if len(errors) == 0:
            bmiVal = weight/ (height**2)
            if bmiVal> 10 and bmiVal<70:
                self.outTxt.setStyleSheet("color : blue")
                self.outTxt.setText(f"مقدار شاخص توده بدنی شما برابر {bmiVal:.3f} است.")
            else:
                self.outTxt.setStyleSheet("font-size: 18pt; color: red")
                self.outTxt.setText("مقادیر واقعی وارد کنید!")

        else:
            self.outTxt.setStyleSheet("font-size: 18pt; color: red")
            errorStr = ""
            for error in errors:
                errorStr += f"{error} \n"
            self.outTxt.setText(errorStr)

        #return to first state:
        errors = []
        self.meterUnit.setChecked(False)
        self.centimeterUnit.setChecked(False)
        self.inchUnit.setChecked(False)
        self.kgUnit.setChecked(False)
        self.gramUnit.setChecked(False)
        self.poundUnit.setChecked(False)
        self.weight.setText("")
        self.height.setText("")
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())